[build]
  publish = "."

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/app.jsx"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "no-cache"

[[headers]]
  for = "/config.js"
  [headers.values]
    Cache-Control = "no-cache"
